# Generated by Django 3.2.25 on 2026-06-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('download', 'Download'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('replace', 'Replace'), ('version_restore', 'Version Restore'), ('password_change', 'Password Change'), ('create', 'Create'), ('assign_permission', 'Assign Permission')], help_text='Action performed', max_length=20)),
                ('object_type', models.CharField(choices=[('User', 'User'), ('Department', 'Department'), ('Role', 'Role'), ('Document', 'Document'), ('Permission', 'Permission')], help_text='Type of object affected', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the object affected', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional description of the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='activity_lo_user_id_7b8207_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='activity_lo_action_de9b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['object_type'], name='activity_lo_object__0ab287_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='activity_lo_timesta_899323_idx'),
        ),
    ]
