# Generated by Django 3.2.25 on 2026-06-19 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('report', 'Report'), ('contract', 'Contract'), ('manual', 'Manual'), ('invoice', 'Invoice'), ('presentation', 'Presentation'), ('other', 'Other')], default='other', help_text='Document category', max_length=20)),
                ('file', models.FileField(help_text='Document file', upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'txt'])])),
                ('file_size', models.BigIntegerField(editable=False, help_text='File size in bytes')),
                ('file_type', models.CharField(editable=False, help_text='File extension', max_length=10)),
                ('version', models.PositiveIntegerField(default=1, help_text='Current version number')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True)),
                ('department', models.ForeignKey(help_text='Department that owns this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='departments.department')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Version number')),
                ('file', models.FileField(help_text='Version file', upload_to='documents/versions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'txt'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True, help_text='Notes about changes in this version')),
                ('document', models.ForeignKey(help_text='Parent document', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_d_categor_2c6923_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['department'], name='documents_d_departm_42fae4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload_date'], name='documents_d_upload__301055_idx'),
        ),
    ]
