# Generated by Django 3.2.25 on 2026-06-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='Role name (e.g., Super Admin, Department Admin, Employee)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Role description and permissions')),
                ('can_create_users', models.BooleanField(default=False)),
                ('can_edit_users', models.BooleanField(default=False)),
                ('can_delete_users', models.BooleanField(default=False)),
                ('can_create_departments', models.BooleanField(default=False)),
                ('can_edit_departments', models.BooleanField(default=False)),
                ('can_delete_departments', models.BooleanField(default=False)),
                ('can_upload_documents', models.BooleanField(default=False)),
                ('can_edit_documents', models.BooleanField(default=False)),
                ('can_delete_documents', models.BooleanField(default=False)),
                ('can_manage_permissions', models.BooleanField(default=False)),
                ('can_view_activity_logs', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['role_name'],
            },
        ),
    ]
