# Generated by Django 3.2.25 on 2026-06-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Role that has access (e.g., super_admin, department_admin, employee)', max_length=20, null=True)),
                ('can_view', models.BooleanField(default=True, help_text='Can view the document')),
                ('can_download', models.BooleanField(default=True, help_text='Can download the document')),
                ('can_edit', models.BooleanField(default=False, help_text='Can edit the document')),
                ('can_delete', models.BooleanField(default=False, help_text='Can delete the document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department that has access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='departments.department')),
                ('document', models.ForeignKey(help_text='Document this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document')),
                ('user', models.ForeignKey(blank=True, help_text='Specific user that has access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'role', 'department', 'user')},
            },
        ),
    ]
